### ISSUE TITLE
TableRow - Improve the UI for disabled row

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material-table#84]
### Current
![image](https://user-images.githubusercontent.com/3138071/28807306-70ce1996-76a7-11e7-859f-4d040e5b054d.png)

### New Look and Feel
![disabled-row](https://user-images.githubusercontent.com/3138071/28807285-48962f22-76a7-11e7-9867-a7262a113285.gif)

### Patched Css Style
```css
tr.disabled * {
opacity: 0.7;
-webkit-touch-callout: none;
-webkit-user-select: none;
-khtml-user-select: none;
-moz-user-select: none;
-ms-user-select: none;
user-select: none;
background: #e9e9e9;
cursor: not-allowed;
}
```
